# Generated by Django 5.0.2 on 2025-05-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_doctor_fields'),
        ('users', '0002_remove_admin_phone_number_alter_admin_is_staff_and_more'),
    ]

    operations = [
    ]
